name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn jest --ci --verbose
      # Publish to NPM registry
      - run: npm run publish-to-npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
