name: Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn jest --ci --verbose
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run Linter
        run: yarn type-check
  