name: Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn jest --ci --verbose
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run Linter
        run: yarn type-check
  
